name:                nsML
version:             0.1.0.0
github:              "meowcolm024/nsML"
license:             BSD3
author:              "Meowcolm024"
maintainer:          "luoyicong1026@live.com"
copyright:           "2021 Meowcolm024"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/meowcolm024/nsML#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1 && < 4

library:
  source-dirs: src

executables:
  nsML-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nsML

tests:
  nsML-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nsML
